[platformio]
src_dir = main

[env:wt32-eth01]
platform = espressif32@6.10.0
board = wt32-eth01
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.embed_files =
    main/web/index.html
    main/web/style.css
    main/web/app.js
build_type = release
